### ISSUE TITLE
Add More Rebindable Keys

### ISSUE THREAD

**Issue by shantanub08** [2called-chaos/gtav-online-ahk#11]
People like myself who use Arrow keys instead of WASD can't use the default script. Because unlike
```
%IGB_Interaction%
%IGB_Phone%
%IGB_PhoneSpecial%
%IGB_Pause%
```
the following keys used in function are not rebindable
```
{Up}
{Down}
{Right}
{Enter} 
```
I fixed it by replacing them respectively with
```
IGB_Up
IGB_Down
IGB_Right
IGB_Enter
```
And defined them in config.ahk (optional, as I've already modified the main.ahk script) But the rule of not modifying the main file gets broken as the update will reset these from corresponding functions. I can't use config.ahk or custom.ahk for this as I get error for duplicate functions. An update replacing these would be very appreciated :) until then I'll keep the updates off. And thanks for making such a complex, yet carefully written macros script. Using this feels like Neo from The Matrix haha

**Comment by 2called-chaos** [comment]
Do you mean you essentially switched WASD with the arrow keys aka you run on arrow keys and use WASD or something else for navigating menus?

I'm not sure if the phone has different bindings than the interaction menu as you haven't listed `left` which is being used when dialing numbers.

It's trivial to make variables out of it but I don't know if I need two sets of bindings for interaction menu and phone navigation

Edit: I would test it but rebinding this many keys in GTA is a huge pita

**Comment by shantanub08** [comment]
> I'm not sure if the phone has different bindings than the interaction menu as you haven't listed left which is being used when dialling numbers.

Besides dialling numbers, left is not used anywhere and I don't use the dialling thing anyway. I guess that's why I didn't mention that in the first place. Sorry for that confusion. I realized that way later

Now that I think about it, I've gotten pretty comfortable with my own script; which is essentially yours, the only difference being {Left}{Right}{Up}{Down} are replaced with {%IGB_Left%}{%IGB_Right%}%IGB_Up%}%IGB_Down%} literally everywhere.

Bottomline being, I changed my mind and closing this issue myself. After spending days on editing your script (ahk noob here) I learned a lot and got comfortable modifying the script myself. So I guess me forking your script instead of telling you to change your og script makes the most sense

**Comment by 2called-chaos** [comment]
As I said it's not a big deal (basically find-and-replace-all) I just need to know whether your changed bindings apply to all navigational menus. That is the same "arrow keys"/WASD for phone navigation, interaction menu and pause menu. Basically is it enough to just `IGB_Up` or do we need it more granular `IGB_PhoneUp, IGB_InteractionUp, etc`

Feel free to work on your fork but I'm happy to improve the base for everyone :)

**Comment by shantanub08** [comment]
> As I said it's not a big deal (basically find-and-replace-all) I just need to know whether your changed bindings apply to all navigational menus. That is the same "arrow keys"/WASD for phone navigation, interaction menu and pause menu. Basically is it enough to just `IGB_Up` or do we need it more granular `IGB_PhoneUp, IGB_InteractionUp, etc`

Yes, it was enough to just replace `{Up}` to `%IGB_Up%` everywhere. But be careful while doing find-and-replace-all as some commented text might also change and if we input case sensitive and curly brackets while find and replace, then we miss out on some in the phone dialing macros, which used to make my player move left/right instead of going left/right/up/down on the phone's dialpad.

I just posted my [latest ahk](https://github.com/shantanub08/gtav-online-ahk/blob/master/GTA%20V%20Online%20Macros.ahk) on my fork in case I couldn't explain myself better

- Changed Macro(s) Triggers
- Changed Macro(s) Order
- Added few of my own (e.g. Spawn free frogger, Return Personal Vehicle Back to Storage)
- Added more rebindable keys

By the way, is it possible not needing to globally declare same IGB Keys for every macro? When you'll see the script, you'll know what I'm talking about

**Comment by 2called-chaos** [comment]
You have two (3 really) options inside functions (macros are global by default). Functions being `func () {}` and macros being essentially goto's `Macro: .... return`

https://www.autohotkey.com/docs/Functions.htm#Global

So you can either decide on declaring all global variables explicitly or defining all local variables explicitly. Another option is to use super-globals (declaring them global in an already global context) which I think makes the most sense but I haven't use them before. From what I understand we just need to declare the IGB variables with global (`global IGB_Up := "Key"`) and that should do it.

I never added it to the Readme but you can also create a `custom.ahk` to organize custom macros and functions without altering the original (besides the config.ahk to change the macro binds). Doesn't really help if you had to change existing macros but allows for adding custom ones whilst still being able to update without losing the custom ones. I need to explain this in the Readme :) But here's an example to get the idea: https://gist.github.com/2called-chaos/dc181a5697ec9e29c439273502028396

> But be careful while doing find-and-replace-all as some commented text might also change

Of course :) My axe-in-the-woods approach is to replace all losely and discard unwanted changes in my git client


I reopened because I will variable-ify all bindings which I should have done from the get go, my friend is a prime example of weird configs (he runs on right mouse button ¯\\\_(ツ)_/¯) 


> Changed Macro(s) Order

This will make it very hard for you to merge any changes if you plan on ever rebasing on this repository. I deliberately chose a single "clusterfuck file" for ease of installation and updating over a more structured, multi-file approach.

**Comment by 2called-chaos** [comment]
In case you are interested in how I did it / how I work on this stuff :) https://www.youtube.com/watch?v=uCobBxk9_Vo&t=20s
